export const usersConstants = {
  ME_REQUEST: 'USERS_ME_REQUEST',
  ME_SUCCESS: 'USERS_ME_SUCCESS',
  ME_FAILURE: 'USERS_ME_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  GET_ALL_REQUEST: 'USERS_GET_ALL_REQUEST',
  GET_ALL_SUCCESS: 'USERS_GET_ALL_SUCCESS',
  GET_ALL_FAILURE: 'USERS_GET_ALL_FAILURE',

  UPDATE_REQUEST: 'USERS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'USERS_UPDATE_FAILURE',

  GET_BY_ID_REQUEST: 'USERS_GET_BY_ID_REQUEST',
  GET_BY_ID_SUCCESS: 'USERS_GET_BY_ID_SUCCESS',
  GET_BY_ID_FAILURE: 'USERS_GET_BY_ID_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE',

  USERS_CLEAN: 'USERS_CLEAN',

};
